version: '3'

services:
  php:
    image: php:7.4-apache
    volumes:
      - ./src:/var/www/html
    ports:
      - 8081:80

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"

volumes:
  jenkins-data:
